QuizViewController and QuizViewModel with mock data
LorenaL9/QuizApp pull request #12
Opened 2022-07-29 11:15 UTC by LorenaL9

https://user-images.githubusercontent.com/94188461/181747731-f7339401-4fc5-45b9-923b-220f290b7a9f.mp4

2022-08-01 08:31 UTC, marinzg requested changes

2022-08-01 08:31 UTC, marinzg commented on QuizApp/Quiz/View/QuizViewController.swift
> +extension QuizViewController: ConstructViewsProtocol {
Please refactor this to use DiffableDataSource and CompositionalLayout.

2022-08-01 08:31 UTC, marinzg commented on QuizApp/Quiz/View/QuizzesCategoriesCollectioonViewCell.swift
> +        case "EASY":
Why isn't this an enum?

2022-08-03 09:03 UTC, marinzg requested changes

2022-08-03 09:03 UTC, marinzg commented on QuizApp/Quiz/View/QuizViewModel.swift
> +    private var history: [QuizModel] = []
Do you plan to remove these when you connect to the API?

2022-08-03 09:03 UTC, marinzg commented on QuizApp/Quiz/View/QuizViewModel.swift
> +            return SelectedCategoryModel(categoryName: category, isSelected: category.id == 0)
No need for `return`

2022-08-03 12:46 UTC, LorenaL9 commented on QuizApp/Quiz/View/QuizViewModel.swift
> +    private var history: [QuizModel] = []
Yes, when I connect to the API I will fetch only quizzes in selected category.

2022-08-08 10:01 UTC, dorastipkovic requested changes

2022-08-08 10:01 UTC, dorastipkovic commented on QuizApp/Quiz/View/QuizzesCategoriesCollectioonViewCell.swift
> +    var score3: UIImageView!
Use StackView for difficulty images.

2022-08-08 14:46 UTC, dorastipkovic requested changes

2022-08-08 14:46 UTC, dorastipkovic commented on QuizApp/Quiz/View/QuizViewController.swift
> +                self?.applyCetegorySnapshot(categories: categories)
typo

2022-08-08 14:46 UTC, dorastipkovic commented on QuizApp/Quiz/View/QuizViewController.swift
> +
You don't need space here. You only need to separate different components.

2022-08-08 14:46 UTC, dorastipkovic commented on QuizApp.xcodeproj/project.pbxproj
> +		C3238B232892CE33005A8DEC /* QuizCollectioonViewCell.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = QuizCollectioonViewCell.swift; sourceTree = "<group>"; };
Typo in file name

2022-08-08 15:22 UTC, dorastipkovic approved these changes

2022-08-09 07:35 UTC, merged