authorization header / app navigation
LorenaL9/QuizApp pull request #22
Opened 2022-08-16 11:36 UTC by LorenaL9

2022-08-17 13:04 UTC, dorastipkovic requested changes
Don't have two separate topics covered in one PR. 
Authorization header should have been one PR, and navigation the other. 
Leave it as is now, but please follow that principle in the future.

2022-08-17 13:04 UTC, dorastipkovic commented on QuizApp/NetworkService/NetworkClient.swift
> +
```suggestion
        if let accessToken = getAccessToken() {
            request.setValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
        }

```

2022-08-17 13:04 UTC, dorastipkovic commented on QuizApp/Leaderboard/Client/LeaderboardClient.swift
> +        return await networkClient.get(header: nil, body: nil, path: .quizLeaderboard, query: query)
Make `header` argument have default value `nil`, like `query` does.

2022-08-18 08:47 UTC, LorenaL9 commented on QuizApp/Leaderboard/Client/LeaderboardClient.swift
> +        return await networkClient.get(header: nil, body: nil, path: .quizLeaderboard, query: query)
I made the same for **body** argument, but only for functions that are using in some client.

2022-08-18 10:00 UTC, dorastipkovic approved these changes

2022-08-30 07:29 UTC, merged