Feature/question screen part1
LorenaL9/QuizApp pull request #24
Opened 2022-08-19 09:59 UTC by LorenaL9

![Simulator Screen Shot - iPhone 13 - 2022-08-19 at 11 57 04](https://user-images.githubusercontent.com/94188461/185594869-0bba253e-4820-4713-8dcf-38f9e668dae5.png)

2022-08-25 14:48 UTC, marinzg requested changes
There's a lot of logic here. Even though it's below limit, you might consider creating only views first, and then feature by feature so you see if it's going to be a lot of changes.

2022-08-25 14:48 UTC, marinzg commented on QuizApp/Question/View/QuestionAnswersViewController.swift
> +    }
You can use swift array functions to make this more readable:
```swift
private func markCorrectAnswer() {
    let correctAnswerView = stackView
        .arrangedSubviews
        .first { view in
            guard let answerView = view as? AnswerView else { return false }

            return answerView.answerId == data.correctAnswerId
        } as? AnswerView

    correctAnswerView?.styleCorrectAnswer()
}
```

2022-08-25 14:48 UTC, marinzg commented on QuizApp/Question/View/QuestionViewController.swift
> +                if !questions.isEmpty {
You can put this condition in the `guard` statement.

2022-08-25 14:48 UTC, marinzg commented on QuizApp/Question/View/QuestionViewController.swift
> +        let stackViewHasSubviews = questionNavigationStackView.arrangedSubviews.isEmpty
You've named this incorrectly. You're checking if the stack view is empty but the name suggests that it's not empty.

Also, you should rename it to `isQuestionNavigationSetUp` because you're deciding whether to update existing views or create new ones.

2022-08-25 14:48 UTC, marinzg commented on QuizApp/Question/View/QuestionViewController.swift
> +        }
Each of these should be a separate function: `createQuestionNavigation` or `updateQuestionNavigation`.

2022-08-25 14:48 UTC, marinzg commented on QuizApp/Question/View/QuestionAnswersViewController.swift
> +}
You should replace all delegates with Combine.
Start with `QuestionAnswersViewController` and add `correctAnswerSelectedSubject` for which you'll call `send` when user selects an answer. You'll need a `correctAnswerSelected` which will be AnyPublisher on which `QuestionsPageViewController` can subscribe. If you repeat that, you'll be able to subscribe in `QuestionViewController` and get the information you need without having delegates.

The idea is that a view controller exposes some information and its parent can subscribe to that instead of becoming a delegate.

2022-08-29 07:07 UTC, LorenaL9 commented on QuizApp/Question/View/Models/Question.swift
> +    let correctAnswer: Bool?
No, I forgot to delete it.

2022-08-29 09:17 UTC, LorenaL9 commented on QuizApp/Question/View/QuestionAnswersViewController.swift
> +    convenience init(data: Question) {
There is no function which can fetch question by questionID.

2022-08-30 08:48 UTC, marinzg requested changes

2022-08-30 08:48 UTC, marinzg commented on QuizApp/Question/View/AnswerView.swift
> +    }
Missing new line.

2022-08-30 08:48 UTC, marinzg commented on QuizApp/AppDependencies.swift
> +
Extra new line.

2022-08-30 08:48 UTC, marinzg commented on QuizApp/Question/View/QuestionViewController.swift
> +    }
You might have misunderstood my previous comment.
Function name was ok - it was telling you that the function is setting question navigation.
Variable name is the incorrect one - it should've been named `isQuestionNavigationSetUp` so when you read condition you know what's going on.

```swift
if isQuestionNavigationSetUp {
    updateQuestionNavigation(questions: questions)
else {
    createQuestionNavigation(questions: questions)
}

// or

isQuestionNavigationSetUp ? 
    updateQuestionNavigation(questions: questions) :
    createQuestionNavigation(questions: questions)
```

2022-08-30 12:05 UTC, marinzg approved these changes

2022-08-30 12:51 UTC, merged