LeaderboardView in SwiftUI
LorenaL9/QuizApp pull request #36
Opened 2022-09-06 14:15 UTC by LorenaL9

![Simulator Screen Shot - iPhone 13 Pro - 2022-09-06 at 16 06 03](https://user-images.githubusercontent.com/94188461/188658486-b10b017f-cabf-4e5e-993b-327fa5f4917c.png)

2022-09-07 12:41 UTC, marinzg requested changes

2022-09-07 12:41 UTC, marinzg commented on QuizApp/Leaderboard/View/SwiftUI/LeaderboardView.swift
> +    @StateObject var viewModel: LeaderboardViewModel
Why `StateObject`?

2022-09-07 15:57 UTC, LorenaL9 commented on QuizApp/Leaderboard/View/SwiftUI/LeaderboardView.swift
> +    @StateObject var viewModel: LeaderboardViewModel
I use @StateObject for viewModel in all views.

2022-09-08 11:12 UTC, marinzg approved these changes

2022-09-08 11:38 UTC, merged