Feature/question view swift UI
LorenaL9/QuizApp pull request #38
Opened 2022-09-07 13:37 UTC by LorenaL9

![Simulator Screen Shot - iPhone 13 Pro - 2022-09-07 at 15 31 32](https://user-images.githubusercontent.com/94188461/188892113-9a6b3945-d315-4395-a0e3-4c45ba83e205.png)

2022-09-08 11:25 UTC, marinzg requested changes

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/AnswerViewSwiftUI.swift
> +struct AnswerViewSwiftUI: View {
Why `SwiftUI` suffix?

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/Models/QuestionNavigation.swift
> +    var correctAnswer: Color
How can variable named `correctAnswer` be of type `Color`?

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/QuestionAnswersView.swift
> +                        }
Can you call `onTapGesture(perform: onAnswered)`?

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/QuestionView.swift
> +            Spacer()
You should break this into multiple computed properties.

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/QuestionView.swift
> +                if question.id == selectedQuestion?.id {
Why not `guard`?

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/QuestionView.swift
> +                    }
I would prefer if you'd created a function `answerSelected(answerId:_)` and call `QuestionAnswersView(question: question, onAnswered: answerSelected)`.

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/QuestionViewModel.swift
> +            }
```swift
question.isSelected ? 
    QuestionNavigation(id: question.id, correctAnswer: answerBackgroundColor, isSelected: true) : 
    question
```

2022-09-08 11:25 UTC, marinzg commented on QuizApp/Question/View/QuestionViewModel.swift
> +            if questionId == question.id {
This should be a `guard`.

2022-09-08 13:08 UTC, LorenaL9 commented on QuizApp/Question/View/QuestionAnswersView.swift
> +                        }
No😉

2022-09-12 11:11 UTC, marinzg requested changes

2022-09-12 11:11 UTC, marinzg commented on QuizApp/Question/View/QuestionAnswersView.swift
> +    @State private var backgroundColor: Color = .lightWhite
Are you using this anywhere?

2022-09-12 11:11 UTC, marinzg commented on QuizApp/Question/View/QuestionViewModel.swift
> +        else { return }
```swift
guard
     let question = questions.filter({ question in question.id == selectedQuestionId}).first
else { return }
```

2022-09-12 11:19 UTC, LorenaL9 commented on QuizApp/Question/View/QuestionAnswersView.swift
> +    @State private var backgroundColor: Color = .lightWhite
No.

2022-09-15 12:45 UTC, marinzg approved these changes

2022-09-15 12:54 UTC, merged